version: "3.8"

services:
  app:
    container_name: coderace-web
    image: coderace-web:latest
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
