version: "3"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: "api"
    command: node built/api/server.js
    restart: always
    ports:
      - "8083:80"
    env_file:
      - .env
    logging:
      driver: "gelf"
    networks:
      - shared-network
volumes:
  redis:
    driver: local

networks:
  shared-network:
    external: true
